### ISSUE TITLE
AttributeError: type object 'tqdm' has no attribute 'wrapattr'

### ISSUE THREAD

**Issue by qinyaolong123** [cainmagi/FFmpeg-Encoder-Decoder-for-Python#5] opened 2022-04-23 14:05 UTC
### Description

```log
AttributeError: type object 'tqdm' has no attribute 'wrapattr'
```

### OS

Should occur on both Linux and Windows.

### Python version

Not specified. This bug is not related to the Python version.

### numpy version

Not specified. This bug is not related to `numpy`.

### mpegCoder version

3.2.3

(Should occur from 3.1.0b0 to 3.2.3)

**Comment by cainmagi** [comment] 2022-04-25 02:49
It seems that the issue is caused by `tqdm`. `tqdm.tqdm.wrapattr` does not exist in `tqdm<=4.40.0`. I guess that this problem can be fixed by

```bash
python -m pip install "tqdm>=4.40.0"
```

However, I think this should be not a neat solution because `tqdm` should not be a dependency of this project. Actually, I have written a check, where the `tqdm` will not be used if it is not installed. The problem exists because I have not considered the variety of `tqdm` APIs.

**If you prefer not to upgrade your `tqdm`, please wait a day, I will upload a new version `mpegCoder==3.2.4`, where this problem will be fixed.**

**Comment by cainmagi** [comment] 2022-04-25 03:19
Good news! It seems that this issue is much easier than I expect to tackle.

Now you can update your `mpegCoder` by

```bash
python -m pip install "mpegCoder>=3.2.4"
```

to test it.

Please give me a day for updating the documentation, because the device where the environment is configured for writing the documentation is not near my hand.

Thank you for reporting the issue! If you find the problem is fixed, please close it. I will close the issue when the documentation is updated.

**Comment by cainmagi** [comment] 2022-04-25 20:14
Close this issue.

Thank you for reporting the bug. Your report has been added to the documentation.

See here;
https://cainmagi.github.io/FFmpeg-Encoder-Decoder-for-Python/docs/troubleshooting/installation#tqdm-has-no-attribute-wrapattr

**Closed as completed by cainmagi** 2022-04-25 20:14 UTC
Labels: bug
